### ISSUE TITLE
Code cleanup.

### ISSUE THREAD

**Issue by Goranaws** [tullamods/Dominos_Cast#7]
I'm currently work to clean and clarify the code. I'll be removing unnecessary files and functions. If you have any requests going forward, please let me know. If you would like me to remove any of the options I've added, I'm willing to do so. I want this module to fit in with your recent updates to Dominos.

**Comment by Tuller** [comment]
Noted.  I've been very busy recently so I've not had a huge amount of time to look over things.

**Comment by Tuller** [comment]
I've tried to fix a lot of the errors that were present (have not gotten them all yet).

**Comment by Goranaws** [comment]
Cool! :)

**Comment by Goranaws** [comment]
I've downloaded what you've posted, and am working to fix errors and reword things for clarity.

**Comment by Goranaws** [comment]
I'm trying an idea you may not want to include: reverse bar growth and reverse cast time. I feel this might being pushing things too far away from simplicity.. I had to add a custom OnUpdate script for the cast bar, and I'm not fond of how big the module is looking now... how big is too big?

**Comment by Tuller** [comment]
That's a complicated question, and usually involves answering the following:
* Do a lot of people want the feature, or am I going to use it myself?
* How difficult will it be to maintain?
* How much of a performance impact will it have?

**Comment by Tuller** [comment]
I've shifted all of the new castbar stuff onto a different branch, https://github.com/tullamods/Dominos_Cast/tree/Castbar2
This is so that I'm able to start pushing out 6.2.0 versions of Dominos today.

**Comment by Goranaws** [comment]
I'm curious to know what you think of everything so far... What needs the most attention right now?

**Comment by Tuller** [comment]
From the top of my head:
The popup menus need a bit of feedback to show selections/mouseover.
The background set one doesn't seem to function when not using SharedMedia.

**Comment by Goranaws** [comment]
I'll see what I can do.

**Comment by Goranaws** [comment]
I'm going to work on things this weekend. I'd like to get this to a releasable state soon...
